- name: Add Vim PPA
  become: yes
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present

- name: Add Git PPA
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Add Alacritty PPA
  become: yes
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present

- name: Add Flat Remix ICON PPA
  become: yes
  apt_repository:
    repo: ppa:daniruiz/flat-remix
    state: present

- name: Does the Google apt file exist?
  command: test -f /etc/apt/sources.list.d/google-chrome.list
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  become: yes
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  become: yes
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: Update cache for packages
  become: yes
  apt:
    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name:
      - htop
      - curl
      - wget 
      - zsh
      - screenfetch
      - jq
      - xclip
      - apt-transport-https 
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - arc-theme
      - mpv
      - vlc
      - gnome-tweak-tool
      - vim
      - git
      - alacritty
      - flat-remix
      - google-chrome-stable
    state: latest

- name: Install Node.js
  become: yes
  snap:
    name:
      - node
    channel: 12/stable
    classic: yes

- name: Add Docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  become: yes
  apt:
    name: docker-ce

- name: Install Docker compose
  become: yes
  shell: |
    if ! [ -f /usr/local/bin/docker-compose ]; then
      curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

      ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      curl -L https://raw.githubusercontent.com/docker/compose/1.25.5/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

      echo "Installed docker-compose"
    fi
    echo "Docker compose installed"

    exit 0

- name: Install addition software
  become: yes
  snap:
    name:
      - telegram-desktop
      - chromium
      - zoom-client
      - mattermost-desktop
      - postman

- name: Install IDEs
  become: yes
  snap:
    name:
      - webstorm
      - intellij-idea-ultimate
      - sublime-text
      - code
    classic: yes

- name: Setup user
  become: yes
  user:
    name: hex
    groups: docker
    append: yes
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
