- name: Add Vim PPA
  become: yes
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present

- name: Add Git PPA
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Add Alacritty PPA
  become: yes
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present


- name: Update cache for packages
  become: yes
  apt:
    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name:
      - htop
      - curl
      - wget 
      - zsh
      - screenfetch
      - jq
      - xclip
      - apt-transport-https 
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - git
      - vim
      - alacritty
    state: latest

- name: Install Node.js
  become: yes
  snap:
    name:
      - node
    channel: 12/stable
    classic: yes

- name: Add Docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  become: yes
  apt:
    name: docker-ce

- name: Install addition software
  become: yes
  snap:
    name:
      - telegram-desktop
      - chromium
      - zoom-client
      - mattermost-desktop
      - postman

- name: Install IDEs
  become: yes
  snap:
    name:
      - webstorm
      - intellij-idea-ultimate
      - sublime-text
      - code
    classic: yes

- name: Setup user
  become: yes
  user:
    name: hex
    groups: docker
    append: yes
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
